ALTER TABLE INCIDENTS
ADD CONSTRAINT CHK_Severity_Level CHECK (Severity_Level_ BETWEEN 1 AND 5);

ALTER TABLE LOCATIONS
ADD CONSTRAINT CHK_House_Num CHECK (House_Num_ > 0);

ALTER TABLE PROCEDURES_PERFORMED
ADD CONSTRAINT CHK_Success_Rate_Enum CHECK (Success_Rate_ IN ('High', 'Medium', 'Low', 'Failed'));